"""Initial migration with fixed studentnumber column

Revision ID: c78b8a3c33bf
Revises: 
Create Date: 2025-10-04 02:04:43.565275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78b8a3c33bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['studentnumber'])
        batch_op.drop_constraint('fk_user_teacher_id', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_teacher_id', 'users', ['teacher_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
