"""update changes from main branch

Revision ID: 206fb8ace46b
Revises: 32e8bf9bbf3d
Create Date: 2025-10-06 07:53:07.359687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206fb8ace46b'
down_revision = '32e8bf9bbf3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_teacher_id', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_teacher_id', 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
