"""Add teacher_id with named constraint

Revision ID: 32e8bf9bbf3d
Revises: 
Create Date: 2025-09-25 00:46:31.400100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e8bf9bbf3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_teacher_id', 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_teacher_id', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
